name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - name: Build all flake outputs
        run: om ci
      - name: What GHC version?
        run: nix develop -c ghc --version
